Repository back-young-company/project-bestwish, pull requests merged in 2025-07, with the labels that each got.

#174 Feature/#162 platform extension
  BestWish.xcodeproj/project.pbxproj
  BestWish/Data/Network/DTO/AblyResponseDTO.swift
  BestWish/Data/Network/Fetcher/AblyFetcher.swift
  BestWish/Data/Network/Fetcher/BrandiFetcher.swift
  BestWish/Data/Network/Fetcher/HiverFetcher.swift
  BestWish/Data/Network/Fetcher/KreamFetcher.swift
  BestWish/Data/Network/Fetcher/MusinsaFetcher.swift
  BestWish/Data/Network/Fetcher/ZigzagFetcher.swift
  BestWish/Data/Network/Fetcher/_29CMFetcher.swift
  BestWish/Data/Network/Fetcher/_4910Fetcher.swift
  BestWish/Data/Network/Manager/ProductSync/Fetcher/AblyFetcher.swift
  BestWish/Data/Network/Manager/ProductSync/Fetcher/MusinsaFetcher.swift
  BestWish/Data/Network/Manager/ProductSync/Fetcher/ZigzagFetcher.swift
  BestWish/Data/Network/Manager/ProductSync/ProductSyncManager.swift
  BestWish/Data/Util/Platform+Util.swift
  BestWish/Data/Util/PlatformEntity+Util.swift
  BestWish/Data/Util/String+Util.swift
  BestWish/Domain/Entity/PlatformEntity.swift
  BestWish/Domain/Interface/ProductDTORepository.swift
  BestWish/Presentation/Extension/PlatformEntity+Extension.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/AnalaysisViewController.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListCell.swift
  BestWish/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
  BestWish/Resource/Assets.xcassets/Platform/brandi.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Platform/brandi.imageset/Frame 1437263263-4.png
  BestWish/Resource/Assets.xcassets/Platform/brandi.imageset/Frame 1437263263@2x-4.png
  BestWish/Resource/Assets.xcassets/Platform/brandi.imageset/Frame 1437263263@3x-4.png
Labels: ✨ Feature, 영웅, 🔥 Fix

#178 Refactor/#168 v1.0.3 home scene section reorganization
  BestWish/App/DIContainer.swift
  BestWish/Domain/Entity/PlatformEntity.swift
  BestWish/Presentation/Extension/NSCollectionLayoutSection+Extension.swift
  BestWish/Presentation/Scene/Home/SectionModel/HomeSectionModel.swift
  BestWish/Presentation/Scene/Home/ViewController/HomeViewController.swift
  BestWish/Presentation/Scene/Home/ViewController/LinkSaveViewController.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/HomeView.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/LinkSaveView.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListEmptyCell.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListEmptyHeaderView.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListFilterCell.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListFilterHeaderView.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListHeaderView.swift
  BestWish/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
  BestWish/Presentation/Scene/Home/ViewModel/LinkSaveViewModel.swift
  BestWishShareExtension/Info.plist
  BestWishShareExtension/Resources/Presentation/Share/ShareView.swift
Labels: 🔨 Refactor, 래훈

#180 Bugfix/#175 previous bugfix
  BestWish/Data/Network/Fetcher/AblyFetcher.swift
  BestWish/Data/Network/Fetcher/BrandiFetcher.swift
  BestWish/Data/Network/Fetcher/HiverFetcher.swift
  BestWish/Data/Network/Fetcher/KreamFetcher.swift
  BestWish/Data/Network/Fetcher/MusinsaFetcher.swift
  BestWish/Data/Network/Fetcher/ZigzagFetcher.swift
  BestWish/Data/Network/Fetcher/_4910Fetcher.swift
  BestWish/Data/Network/Manager/ProductSync/ProductSyncManager.swift
  BestWish/Domain/Error/AppError.swift
  BestWish/Domain/Error/PlatformError.swift
  BestWish/Domain/UseCase/AnalysisUseCase.swift
  BestWish/Presentation/Extension/AppError+Extension.swift
  BestWish/Presentation/Extension/PlatformEntity+Extension.swift
  BestWish/Presentation/Extension/UIImage+Extension.swift
  BestWish/Presentation/Scene/Anlaysis/SectionModel/AnalysisSection.swift
  BestWish/Presentation/Scene/Anlaysis/ViewModel/AnalysisViewModel.swift
  BestWish/Presentation/Scene/Camera/ViewController/ImageEditViewController.swift
  BestWish/Presentation/Scene/Camera/ViewModel/ImageEditViewModel.swift
  BestWish/Presentation/Scene/Home/SectionModel/HomeSectionModel.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/PlatformShortcutCell.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListCell.swift
  BestWish/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
  BestWish/Presentation/Scene/Home/ViewModel/WishListEditViewModel.swift
  BestWish/Presentation/Scene/TabBar/ViewController/TabBarViewController.swift
  BestWishShareExtension/Resources/Presentation/Share/ShareViewModel.swift
Labels: 🐞 BugFix

#189 Fix/ #188 - 온보딩 첫번째 이미지 수정
  BestWish/Resource/Assets.xcassets/Onboarding/onboardingFirst.imageset/onboardingFirst.png
  BestWish/Resource/Assets.xcassets/Onboarding/onboardingFirst.imageset/onboardingFirst@2x.png
  BestWish/Resource/Assets.xcassets/Onboarding/onboardingFirst.imageset/onboardingFirst@3x.png
Labels: 세준, 🔥 Fix

#193 Fix/#190 v.1.0.4 keychain 로직 개선, 회원탈퇴 UX 개선
  BestWishData/Data/Network/Error/AuthError.swift
  BestWishData/Data/Network/Manager/OAuth/SupabaseOAuthManagerImpl.swift
  BestWishPresentation/Presentation/Scene/Alert/AlertViewController.swift
  BestWishPresentation/Presentation/Scene/MyPage/UserInfoManagement/ViewController/Subview/UserInfoManagementView.swift
  BestWishPresentation/Presentation/Scene/MyPage/UserInfoManagement/ViewController/UserInfoManagementViewController.swift
  BestWishPresentation/Presentation/Scene/MyPage/UserInfoManagement/ViewModel/UserInfoManagementViewModel.swift
Labels: 🔨 Refactor, 세준, 🔥 Fix

#195 chore: #191 - 모든 모듈에서 빌드버전 맞춤
  BestWish.xcodeproj/project.pbxproj
Labels: ⚙ Setting, 영웅

#211 chore: User-Defined 수정
  BestWish.xcodeproj/project.pbxproj
Labels: ⚙ Setting

#213 Feature/#212 platform link alert update
  BestWishData/Data/Util/String+Util.swift
  BestWishPresentation/Presentation/Extension/PlatformEntity+Extension.swift
  BestWishPresentation/Presentation/Extension/UIViewController+Extension.swift
  BestWishPresentation/Presentation/Scene/Anlaysis/ViewModel/AnalysisViewModel.swift
  BestWishPresentation/Presentation/Scene/Home/ViewController/HomeViewController.swift
Labels: ✨ Feature, 래훈
