Repository back-young-company/project-bestwish, pull requests merged in 2025-06, with the labels that each got.

#2 Feature/#1 extension
  BestWish.xcodeproj/project.pbxproj
  BestWish.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  BestWish/Presentation/Extension/UIColor+Extension.swift
  BestWish/Presentation/Extension/UIFont+Extension.swift
  BestWish/Presentation/Extension/UIStackView+Extension.swift
  BestWish/Presentation/Extension/UIView+Extension.swift
  BestWish/Resource/Fonts/Pretendard-Black.otf
  BestWish/Resource/Fonts/Pretendard-Bold.otf
  BestWish/Resource/Fonts/Pretendard-ExtraBold.otf
  BestWish/Resource/Fonts/Pretendard-ExtraLight.otf
  BestWish/Resource/Fonts/Pretendard-Light.otf
  BestWish/Resource/Fonts/Pretendard-Medium.otf
  BestWish/Resource/Fonts/Pretendard-Regular.otf
  BestWish/Resource/Fonts/Pretendard-SemiBold.otf
  BestWish/Resource/Fonts/Pretendard-Thin.otf
  BestWish/Resource/Info.plist
Labels: ✨ Feature, 수현

#8 Feature/#7 dto
  BestWish/Data/Network/DTO/ProductDTO.swift
  BestWish/Data/Network/DTO/UserDTO.swift
Labels: ✨ Feature, 수현

#10 setting: #9 - .xcconfig 파일 설정
  .gitignore
  BestWish.xcodeproj/project.pbxproj
  BestWish/Presentation/Scene/Dummy/ViewController/DummyViewController.swift
  BestWish/Resource/Info.plist
Labels: ⚙ Setting, 수현

#13 setting: #12 - 프로젝트 셋팅추가
  BestWish.xcodeproj/project.pbxproj
  BestWish.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  BestWish/App/ko.lproj/LaunchScreen.strings
  BestWish/Presentation/Extension/Bundle+Extension.swift
  BestWish/Presentation/Extension/CGFloat+Extension.swift
  BestWish/Presentation/Extension/UIImage+Extension.swift
  BestWish/Resource/Info.plist
Labels: ⚙ Setting

#16 setting: #15 - 커스텀 컬러 추가
  BestWish/Presentation/Extension/UIColor+Extension.swift
Labels: ⚙ Setting, 수현

#20 Feature/#5 커스텀 탭바 구현
  BestWish/Presentation/Scene/TabBar/View/TabBarView.swift
  BestWish/Presentation/Scene/TabBar/ViewController/TabBarViewController.swift
  BestWish/Resource/Assets.xcassets/Tabbar/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de1.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de1.imageset/camera_de1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de2.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de2.imageset/camera_de2 1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de2.imageset/camera_de2 2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de2.imageset/camera_de2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de3.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de3.imageset/camera_de3.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_de3.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se1.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se1.imageset/camera_se1 1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se1.imageset/camera_se1 2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se1.imageset/camera_se1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se2.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se2.imageset/camera_se2 1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se2.imageset/camera_se2 2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se2.imageset/camera_se2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se3.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se3.imageset/camera_se3 1.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se3.imageset/camera_se3 2.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se3.imageset/camera_se3.png
  BestWish/Resource/Assets.xcassets/Tabbar/camera_se3.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_de1.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/home_de1.imageset/home_de1.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_de1.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_de2.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/home_de2.imageset/home_de2.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_de2.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_de3.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/home_de3.imageset/home_de3.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_de3.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se1.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/home_se1.imageset/home_se1 1.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se1.imageset/home_se1 2.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se1.imageset/home_se1.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se1.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se3.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Tabbar/home_se3.imageset/home_se3 1.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se3.imageset/home_se3 2.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se3.imageset/home_se3.png
  BestWish/Resource/Assets.xcassets/Tabbar/home_se3.png
Labels: ✨ Feature, 영웅

#18 Feature/#14 버튼 컴포넌트 구현
  BestWish/Presentation/Component/AppButton.swift
  BestWish/Presentation/Extension/UIStackView+Extension.swift
Labels: ✨ Feature, 수현

#22 Feature/#19 my page UI
  BestWish.xcodeproj/project.pbxproj
  BestWish.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  BestWish/Presentation/Display/AccountDisplay.swift
  BestWish/Presentation/Extension/ReuseIdentifier.swift
  BestWish/Presentation/Extension/UIViewController+Extension.swift
  BestWish/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift
  BestWish/Presentation/Scene/MyPage/ViewController/Subview/MyPageCell.swift
  BestWish/Presentation/Scene/MyPage/ViewController/Subview/MyPageHeaderView.swift
  BestWish/Presentation/Scene/MyPage/ViewController/Subview/MyPageSection.swift
  BestWish/Presentation/Scene/MyPage/ViewController/Subview/MyPageView.swift
  BestWish/Presentation/Scene/MyPage/ViewModel/MyPageViewModel.swift
Labels: ✨ Feature, 수현

#26 Feature/#11 social login 기능 구현
  BestWish.xcodeproj/project.pbxproj
  BestWish.xcodeproj/xcshareddata/xcschemes/BestWish.xcscheme
  BestWish/BestWish.entitlements
  BestWish/Data/KeyChain/Manager/KeyChainManager.swift
  BestWish/Data/KeyChain/Manager/Token.swift
  BestWish/Data/Network/Manager/SocialLogin/Apple/AppleLogin+Extension.swift
  BestWish/Data/Network/Manager/SocialLogin/Apple/AppleLogin.swift
  BestWish/Data/Network/Manager/SocialLogin/Kakao/KakaoLogin.swift
  BestWish/Data/Network/Manager/SupabaseOAuthManager.swift
  BestWish/Presentation/Extension/Bundle+Extension.swift
  BestWish/Presentation/Scene/Login/ViewController/LoginViewController.swift
  BestWish/Presentation/Scene/Login/ViewController/Subview/LoginView.swift
  BestWish/Presentation/Scene/Login/ViewModel/LoginViewModel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingView.swift
  BestWish/Presentation/Scene/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: ✨ Feature, 세준

#27 Feature/#23 profile update UI
  BestWish/Presentation/Component/AppButton.swift
  BestWish/Presentation/Component/InfoLabel.swift
  BestWish/Presentation/Component/PaddingLabel.swift
  BestWish/Presentation/Component/VerticalStackView.swift
  BestWish/Presentation/Display/AccountDisplay.swift
  BestWish/Presentation/Extension/UITextField+Extension.swift
  BestWish/Presentation/Extension/UIViewController+Extension.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ProfileUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ProfileUpdateViewModel.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/Subview/ProfileUpdateView.swift
  BestWish/Presentation/Scene/MyPage/ViewController/MyPageViewController.swift
  BestWish/Presentation/Scene/MyPage/ViewController/Subview/MyPageHeaderView.swift
  BestWish/Presentation/Scene/MyPage/ViewModel/MyPageViewModel.swift
  BestWish/Presentation/Scene/ProfileSheet/ProfileSheetViewController.swift
  BestWish/Presentation/Scene/ProfileSheet/ProfileType.swift
  BestWish/Presentation/Scene/ProfileSheet/Suview/ProfileSheetCell.swift
  BestWish/Presentation/Scene/ProfileSheet/Suview/ProfileSheetView.swift
  BestWish/Resource/Assets.xcassets/Profile/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/ProfileA.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/ProfileA.imageset/ProfileA.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileA.imageset/ProfileA@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileA.imageset/ProfileA@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileB.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/ProfileB.imageset/ProfileB.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileB.imageset/ProfileB@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileB.imageset/ProfileB@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileC.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/ProfileC.imageset/ProfileC.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileC.imageset/ProfileC@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileC.imageset/ProfileC@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileD.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/ProfileD.imageset/ProfileD.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileD.imageset/ProfileD@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileD.imageset/ProfileD@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileE.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/ProfileE.imageset/ProfileE.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileE.imageset/ProfileE@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileE.imageset/ProfileE@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileF.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/ProfileF.imageset/ProfileF.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileF.imageset/ProfileF@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileF.imageset/ProfileF@3x.png
Labels: ✨ Feature, 수현

#34 Feature/#21 login onboarding UI
  BestWish/Presentation/Component/AppButton.swift
  BestWish/Presentation/Component/HorizontalStackView.swift
  BestWish/Presentation/Component/PaddingTextField.swift
  BestWish/Presentation/Display/OnboardingDisplay.swift
  BestWish/Presentation/Extension/UIColor+Extension.swift
  BestWish/Presentation/Scene/DatePicker/DatePickerBottomSheetViewController.swift
  BestWish/Presentation/Scene/DatePicker/SubView/DatePickerBottomSheetView.swift
  BestWish/Presentation/Scene/Login/ViewController/LoginViewController.swift
  BestWish/Presentation/Scene/Login/ViewController/Subview/LoginView.swift
  BestWish/Presentation/Scene/Login/ViewModel/LoginViewModel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/BirthSelectionView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/GenderSelectionView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/NicknameInputView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/OnboardingHeaderView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/OnboardingText.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/PageInfoLabel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/RadioButton.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingFirstView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingSecondView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingView.swift
  BestWish/Presentation/Scene/Onboarding/ViewModel/OnboardingViewModel.swift
  BestWish/Resource/Assets.xcassets/Login/Contents.json
  BestWish/Resource/Assets.xcassets/Login/appleLogin.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Login/appleLogin.imageset/appleLogin.png
  BestWish/Resource/Assets.xcassets/Login/appleLogin.imageset/appleLogin@2x.png
  BestWish/Resource/Assets.xcassets/Login/appleLogin.imageset/appleLogin@3x.png
  BestWish/Resource/Assets.xcassets/Login/kakaoLogin.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Login/kakaoLogin.imageset/kakaoLogin.png
  BestWish/Resource/Assets.xcassets/Login/kakaoLogin.imageset/kakaoLogin@2x.png
  BestWish/Resource/Assets.xcassets/Login/kakaoLogin.imageset/kakaoLogin@3x.png
  BestWish/Resource/Assets.xcassets/Login/loginLogo.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Login/loginLogo.imageset/loginLogo.png
  BestWish/Resource/Assets.xcassets/Login/loginLogo.imageset/loginLogo@2x.png
  BestWish/Resource/Assets.xcassets/Login/loginLogo.imageset/loginLogo@3x.png
  BestWish/Resource/Assets.xcassets/Onboarding/Contents.json
  BestWish/Resource/Assets.xcassets/Onboarding/calendar.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Onboarding/calendar.imageset/calendar.png
  BestWish/Resource/Assets.xcassets/Onboarding/calendar.imageset/calendar@2x.png
  BestWish/Resource/Assets.xcassets/Onboarding/calendar.imageset/calendar@3x.png
  BestWish/Resource/Assets.xcassets/Onboarding/radioOff.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Onboarding/radioOff.imageset/radioOff.png
  BestWish/Resource/Assets.xcassets/Onboarding/radioOff.imageset/radioOff@2x.png
  BestWish/Resource/Assets.xcassets/Onboarding/radioOff.imageset/radioOff@3x.png
  BestWish/Resource/Assets.xcassets/Onboarding/radioOn.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Onboarding/radioOn.imageset/radioOn.png
  BestWish/Resource/Assets.xcassets/Onboarding/radioOn.imageset/radioOn@2x.png
  BestWish/Resource/Assets.xcassets/Onboarding/radioOn.imageset/radioOn@3x.png
Labels: ✨ Feature, 세준

#38 Feature/#37 update user info
  BestWish/Presentation/Display/OnboardingDisplay.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ProfileUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/Subview/UserInfoManagementView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/UserInfoManagementViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/Subview/UserInfoUpdateView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/UserInfoUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewModel/UserInfoUpdateViewModel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/BirthSelectionView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/GenderSelectionView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  BestWish/Presentation/Scene/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: ✨ Feature, 수현

#40 Feature/#39 tab bar show hidden
  BestWish/Presentation/Extension/UIViewController+Extension.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/MyPageViewController.swift
  BestWish/Presentation/Scene/TabBar/View/TabBarView.swift
  BestWish/Presentation/Scene/TabBar/ViewController/TabBarViewController.swift
Labels: ✨ Feature, 수현

#55 hotfix: #54: 다크모드, iPad LandScape 모드 제거
  BestWish.xcodeproj/project.pbxproj
Labels: 🔥 Hotfix, 수현

#56 Feature/#53 문의사항 기능 구현
  BestWish/Presentation/Extension/UIViewController+Extension.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/EmailConstants.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/MyPageViewController.swift
Labels: ✨ Feature, 수현

#57 Feature/#46 add iq keyboard manager
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/AppDelegate.swift
  BestWish/Presentation/Component/PaddingTextField.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/NicknameInputView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/OnboardingHeaderView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingSecondView.swift
  BestWish/Resource/Info.plist
Labels: ✨ Feature, 세준

#63 fix: #45 - 온보딩 radio버튼 UI 버그 수정
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/BirthSelectionView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/RadioButton.swift
Labels: 🐞 BugFix, 세준

#67 Feature/#32 core ml analysis
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/SceneDelegate.swift
  BestWish/Domain/Model/LabelData.swift
  BestWish/Presentation/Display/LabelDataDisplay.swift
  BestWish/Presentation/Extension/UIImage+Extension.swift
  BestWish/Presentation/Scene/Anlaysis/AnalysisModel/AnalysisSection.swift
  BestWish/Presentation/Scene/Anlaysis/View/AnalaysisView.swift
  BestWish/Presentation/Scene/Anlaysis/View/Cell/AttributeCell.swift
  BestWish/Presentation/Scene/Anlaysis/View/Cell/KeywordCell.swift
  BestWish/Presentation/Scene/Anlaysis/View/SegmentControlHeaderView.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/AnalaysisViewController.swift
  BestWish/Presentation/Scene/Anlaysis/ViewModel/AnalysisViewModel.swift
  BestWish/Presentation/Scene/Camera/View/ImageEditView.swift
  BestWish/Presentation/Scene/Camera/ViewController/CameraViewController.swift
  BestWish/Presentation/Scene/Camera/ViewController/ImageEditViewController.swift
  BestWish/Presentation/Scene/Camera/ViewModel/ImageEditViewModel.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/PlatformShortcut/PlatformShortcutCell.swift
  BestWish/Presentation/Scene/TabBar/ViewController/TabBarViewController.swift
  BestWish/Resource/BestWidhClassfication.mlmodel
Labels: ✨ Feature, 🔨 Refactor, 영웅

#70 Feature/#65 mypage logic
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/DIContainer.swift
  BestWish/App/SceneDelegate.swift
  BestWish/Data/Network/DTO/UserDTO.swift
  BestWish/Data/Network/Manager/SocialLogin/Supabase/UploadSupabase.swift
  BestWish/Data/Network/Manager/Supabase/SupabaseUserInfoManager.swift
  BestWish/Data/Repository/UserInfoRepositoryImpl.swift
  BestWish/Domain/Entity/User.swift
  BestWish/Domain/Interface/UserInfoRepository.swift
  BestWish/Domain/UseCase/UserInfoUseCase.swift
  BestWish/Presentation/Component/AppButton.swift
  BestWish/Presentation/Display/AccountDisplay.swift
  BestWish/Presentation/Display/UserInfoDisplay.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/MyPageViewController.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/Subview/MyPageHeaderView.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewModel/MyPageViewModel.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ProfileUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ProfileUpdateViewModel.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/Subview/ProfileUpdateView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/UserInfoManagementViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/Subview/UserInfoUpdateView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/UserInfoUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewModel/UserInfoUpdateViewModel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingSecondView.swift
  BestWish/Presentation/Scene/Onboarding/ViewModel/OnboardingViewModel.swift
  BestWish/Presentation/Scene/ProfileSheet/Suview/ProfileSheetView.swift
Labels: ✨ Feature, 🐞 BugFix, 수현

#74 feature: #73 -위시 리스트 조회 로직 수정
  BestWish/Data/Network/DTO/ProductDTO.swift
  BestWish/Data/Network/Manager/Supabase/SupabaseManager.swift
  BestWish/Data/Repository/WishListRepositoryImpl.swift
  BestWish/Domain/Interface/WishListRepository.swift
  BestWish/Domain/UseCase/WishListUseCase.swift
Labels: ✨ Feature, 수현

#75 Feature/#71 - 런치스크린, 앱아이콘 적용
  BestWish/App/AppDelegate.swift
  BestWish/App/Base.lproj/LaunchScreen.storyboard
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/1024.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/114.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/120.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/180.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/29.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/40.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/57.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/58.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/60.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/80.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/87.png
  BestWish/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  BestWish/Resource/Assets.xcassets/LaunchScreen/Contents.json
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchLogo.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchLogo.imageset/launchLogo.png
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchLogo.imageset/launchLogo@2x.png
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchLogo.imageset/launchLogo@3x.png
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchText.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchText.imageset/launchText.png
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchText.imageset/launchText@2x.png
  BestWish/Resource/Assets.xcassets/LaunchScreen/launchText.imageset/launchText@3x.png
Labels: ✨ Feature, 세준

#82 Fix/#78 - 로그인 플로우 수정
  BestWish/App/SceneDelegate.swift
  BestWish/Data/Network/Error/AuthError.swift
  BestWish/Data/Network/Manager/SupabaseOAuthManager.swift
  BestWish/Data/Repository/UserInfoRepositoryImpl.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/Subview/UserInfoManagementView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/UserInfoManagementViewController.swift
Labels: 🐞 BugFix, 세준

#84 Feature/#79 mypage error
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/MyPageViewController.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/Subview/MyPageHeaderView.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/Subview/MyPageView.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewModel/MyPageViewModel.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ProfileUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ProfileUpdateViewModel.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/Subview/MyPageRowView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/Subview/UserInfoManagementView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/UserInfoManagementViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewModel/UserInfoManagementViewModel.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/Subview/UserInfoUpdateView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/UserInfoUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewModel/UserInfoUpdateViewModel.swift
  BestWish/Presentation/Scene/ProfileSheet/ProfileSheetViewController.swift
  BestWish/Presentation/Scene/ProfileSheet/Suview/ProfileSheetView.swift
Labels: ✨ Feature, 🔨 Refactor, 수현

#85 Feature/#68 move other platform
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/DIContainer.swift
  BestWish/Data/Repository/CoreMLRepositoryImpl.swift
  BestWish/Data/Util/UIImage+Util.swift
  BestWish/Domain/Error/PlatformError.swift
  BestWish/Domain/Interface/CoreMLRepository.swift
  BestWish/Domain/UseCase/AnalysisUseCase.swift
  BestWish/Domain/UseCase/CoreMLUseCase.swift
  BestWish/Presentation/Extension/UIImage+Extension.swift
  BestWish/Presentation/Scene/Anlaysis/AnalysisModel/AnalysisSection.swift
  BestWish/Presentation/Scene/Anlaysis/View/AnalaysisView.swift
  BestWish/Presentation/Scene/Anlaysis/View/Cell/AttributeCell.swift
  BestWish/Presentation/Scene/Anlaysis/View/Cell/KeywordCell.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/AnalaysisViewController.swift
  BestWish/Presentation/Scene/Anlaysis/ViewModel/AnalysisViewModel.swift
  BestWish/Presentation/Scene/Camera/ViewController/CameraViewController.swift
  BestWish/Presentation/Scene/Camera/ViewController/ImageEditViewController.swift
  BestWish/Presentation/Scene/Camera/ViewModel/ImageEditViewModel.swift
  BestWish/Presentation/Scene/Dummy/ViewController/MyWebViewController.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/HomeSection.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/PlatformImage.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/ShopPlatform.swift
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor, 영웅

#104 Setting/#101 ci cd
  .github/secrets/BestWish_Certification.p12.gpg
  .github/secrets/BestWish_GitHub_Actions.mobileprovision.gpg
  .github/secrets/BestWish_GitHub_Actions_ShareExtension.mobileprovision.gpg
  .github/workflows/buildAndTest.yml
  .github/workflows/deploy.yml
Labels: ⚙ Setting, 🌏 Deploy, ✅ Test, 영웅

#105 Setting/#101 ci cd
  BestWish.xcodeproj/project.pbxproj
  ExportOptions.textClipping
Labels: ⚙ Setting, 🌏 Deploy, 영웅

#106 [CI/CD] - 테스트 플라이트 배포
  BestWish.xcodeproj/project.pbxproj
  ExportOptions.textClipping
Labels: 🌏 Deploy, 영웅

#107 setting: #101 - ExprtOptions -> plist로 수정
  ExportOptions.plist
Labels: ⚙ Setting, 🌏 Deploy, 영웅

#100 refactor: #99 - 프로필 이미지 변경
  BestWish/Resource/Assets.xcassets/Profile/ProfileB.imageset/ProfileB.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileB.imageset/ProfileB@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileB.imageset/ProfileB@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileC.imageset/ProfileC.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileC.imageset/ProfileC@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileC.imageset/ProfileC@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileD.imageset/ProfileD.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileD.imageset/ProfileD@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileD.imageset/ProfileD@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileE.imageset/ProfileE.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileE.imageset/ProfileE@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileE.imageset/ProfileE@3x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileF.imageset/ProfileF.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileF.imageset/ProfileF@2x.png
  BestWish/Resource/Assets.xcassets/Profile/ProfileF.imageset/ProfileF@3x.png
Labels: 🔨 Refactor, 수현

#98 Fix/#97 onboarding memory leak
  BestWish/Data/Network/Manager/SocialLogin/Apple/AppleLogin.swift
  BestWish/Data/Network/Manager/SocialLogin/Kakao/KakaoLogin.swift
  BestWish/Data/Network/Manager/SupabaseOAuthManager.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
Labels: 🐞 BugFix, 🔨 Refactor, 세준

#115 Refactor/#113 v1.0.1 quarang
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/DIContainer.swift
  BestWish/App/SceneDelegate.swift
  BestWish/Data/Network/Error/CoreMLError.swift
  BestWish/Data/Network/Manager/CoreML/CoreMLManager.swift
  BestWish/Data/Repository/CoreMLRepositoryImpl.swift
  BestWish/Data/Repository/WishListRepositoryImpl.swift
  BestWish/Domain/Interface/CoreMLRepository.swift
  BestWish/Domain/Model/LabelData.swift
  BestWish/Domain/UseCase/AnalysisUseCase.swift
  BestWish/Domain/UseCase/CoreMLUseCase.swift
  BestWish/Presentation/Display/LabelDataDisplay.swift
  BestWish/Presentation/Scene/Anlaysis/SectionModel/AnalysisSection.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/AnalaysisViewController.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/Resuable/AttributeCell.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/Resuable/KeywordCell.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/Resuable/SectionBackgroundDecorationView.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/Resuable/SegmentControlHeaderView.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/SubView/AnalaysisView.swift
  BestWish/Presentation/Scene/Anlaysis/ViewModel/AnalysisViewModel.swift
  BestWish/Presentation/Scene/Camera/ViewController/CameraViewController.swift
  BestWish/Presentation/Scene/Camera/ViewController/ImageEditViewController.swift
  BestWish/Presentation/Scene/Camera/ViewController/SubView/CameraView.swift
  BestWish/Presentation/Scene/Camera/ViewController/SubView/ImageEditView.swift
  BestWish/Presentation/Scene/Camera/ViewModel/CameraViewModel.swift
  BestWish/Presentation/Scene/Camera/ViewModel/ImageEditViewModel.swift
  BestWish/Presentation/Scene/TabBar/View/TabBarView.swift
  BestWish/Presentation/Scene/TabBar/ViewController/TabBarViewController.swift
Labels: 🔨 Refactor, 영웅

#119 ci-cd: #118 - 테스트 코드 및 배포 자동화 규칙 변경
  .github/workflows/buildAndTest.yml
Labels: ⚙ Setting, 🌏 Deploy, 영웅

#123 ci-cd: #118 - buildAndTest.yml 추가
  .github/workflows/buildAndTest.yml
Labels: ⚙ Setting, 🌏 Deploy, 영웅

#127 Refactor/#111 v1.0.1 yimkeul
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/DIContainer.swift
  BestWish/App/DummyCoordinator.swift
  BestWish/App/SceneDelegate.swift
  BestWish/Data/KeyChain/Error/KeyChainError.swift
  BestWish/Data/KeyChain/Manager/KeyChainManager.swift
  BestWish/Data/Network/Error/AuthError.swift
  BestWish/Data/Network/Manager/SocialLogin/Apple/AppleLogin+Extension.swift
  BestWish/Data/Network/Manager/SocialLogin/Apple/AppleLogin.swift
  BestWish/Data/Network/Manager/SocialLogin/Kakao/KakaoLogin.swift
  BestWish/Data/Network/Manager/SocialLogin/Supabase/UploadSupabase.swift
  BestWish/Data/Network/Manager/SupabaseOAuthManager.swift
  BestWish/Data/Repository/AccountRepositoryImpl.swift
  BestWish/Data/Util/Bundle+Util.swift
  BestWish/Domain/Entity/SocialType.swift
  BestWish/Domain/Error/AppError.swift
  BestWish/Domain/Interface/AccountRepository.swift
  BestWish/Domain/UseCase/AccountUseCase.swift
  BestWish/Presentation/Extension/AppError+Extension.swift
  BestWish/Presentation/Extension/CGFloat+Extension.swift
  BestWish/Presentation/Scene/DatePicker/ViewController/DatePickerBottomSheetViewController.swift
  BestWish/Presentation/Scene/DatePicker/ViewController/SubView/DatePickerBottomSheetView.swift
  BestWish/Presentation/Scene/Login/ViewController/LoginViewController.swift
  BestWish/Presentation/Scene/Login/ViewModel/LoginViewModel.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewModel/MyPageViewModel.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ViewController/Subview/ProfileUpdateView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewModel/UserInfoManagementViewModel.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/Subview/UserInfoUpdateView.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/UserInfoUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewModel/UserInfoUpdateViewModel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/BirthSelectionView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/GenderSelectionView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/IntroTextStackView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/NicknameInputView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/OnboardingHeaderView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/OnboardingText.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/PageInfoLabel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Component/RadioButton.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingFirstView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingSecondView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingView.swift
  BestWish/Presentation/Scene/Onboarding/ViewModel/OnboardingViewModel.swift
  BestWish/Presentation/Scene/PDFViewer/PDFViewController.swift
  BestWish/Presentation/Scene/Policy/PolicyViewController.swift
  BestWish/Presentation/Scene/Policy/Subview/PolicyBottomSheetView.swift
  BestWish/Presentation/Scene/Policy/ViewModel/PolicyViewModel.swift
  BestWish/Resource/Info.plist
  BestWishShareExtension/Info.plist
Labels: 🔨 Refactor, 세준

#129 Test/#121 마이페이지 뷰 모델 테스트 코드 작성
  BestWish/Presentation/Scene/MyPage/MyPageMain/SectionModel/MyPageSection.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/MyPageViewController.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewModel/MyPageViewModel.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ViewModel/ProfileUpdateViewModel.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewModel/UserInfoUpdateViewModel.swift
  BestWishTests/MyPage/ViewModelTests/Mock/MockAccountUseCase.swift
  BestWishTests/MyPage/ViewModelTests/Mock/MockUserInfoUseCase.swift
  BestWishTests/MyPage/ViewModelTests/MyPageViewModelTests.swift
  BestWishTests/MyPage/ViewModelTests/ProfileUpdateViewModelTests.swift
  BestWishTests/MyPage/ViewModelTests/UserInfoManagementViewModelTests.swift
  BestWishTests/MyPage/ViewModelTests/UserInfoUpdateViewModelTests.swift
Labels: ✅ Test, 수현

#138 Refactor/#135 v1.0.1 yimkeul
  BestWish/App/SceneDelegate.swift
  BestWish/Data/KeyChain/Error/KeyChainError.swift
  BestWish/Data/Network/Error/AuthError.swift
  BestWish/Data/Network/Manager/SocialLogin/Apple/AppleLogin.swift
  BestWish/Data/Network/Manager/SocialLogin/Kakao/KakaoLogin.swift
  BestWish/Data/Network/Manager/SupabaseOAuthManager.swift
  BestWish/Data/Repository/AccountRepositoryImpl.swift
  BestWish/Domain/Interface/AccountRepository.swift
  BestWish/Domain/UseCase/AccountUseCase.swift
  BestWish/Presentation/Scene/Login/ViewController/LoginViewController.swift
  BestWish/Presentation/Scene/Login/ViewModel/LoginViewModel.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/MyPageViewController.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewModel/MyPageViewModel.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewController/UserInfoManagementViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoManagement/ViewModel/UserInfoManagementViewModel.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/OnboardingViewController.swift
  BestWish/Presentation/Scene/Onboarding/ViewModel/OnboardingViewModel.swift
Labels: 🔨 Refactor, 세준

#136 Test/#131 UserInfoUseCase 테스트
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/DIContainer.swift
  BestWish/Data/Network/Manager/Supabase/SupabaseUserInfoManager.swift
  BestWish/Data/Repository/UserInfoRepositoryImpl.swift
  BestWish/Domain/Entity/SocialType.swift
  BestWish/Domain/Entity/User.swift
  BestWish/Domain/Interface/UserInfoRepository.swift
  BestWish/Domain/UseCase/UserInfoUseCase.swift
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewModel/MyPageViewModel.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ViewModel/ProfileUpdateViewModel.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewController/UserInfoUpdateViewController.swift
  BestWish/Presentation/Scene/MyPage/UserInfoUpdate/ViewModel/UserInfoUpdateViewModel.swift
  BestWishShareExtension/Resources/Presentation/Share/ShareViewController.swift
  BestWishTests/BestWishTests.swift
  BestWishTests/RepositoryTests/UserInfoRepository/Mock/MockSupabaseUserInfoManager.swift
  BestWishTests/RepositoryTests/UserInfoRepository/UserInfoRepositoryTests.swift
  BestWishTests/UseCaseTests/UserInfoUseCase/Mock/MockUserInfoRepository.swift
  BestWishTests/UseCaseTests/UserInfoUseCase/UserInfoUseCaseTests.swift
  BestWishTests/ViewModelTests/MyPageViewModel/Mock/MockAccountUseCase.swift
  BestWishTests/ViewModelTests/MyPageViewModel/Mock/MockUserInfoUseCase.swift
  BestWishTests/ViewModelTests/MyPageViewModel/MyPageViewModelTests.swift
  BestWishTests/ViewModelTests/MyPageViewModel/ProfileUpdateViewModelTests.swift
  BestWishTests/ViewModelTests/MyPageViewModel/UserInfoManagementViewModelTests.swift
  BestWishTests/ViewModelTests/MyPageViewModel/UserInfoUpdateViewModelTests.swift
Labels: ✅ Test, 수현

#141 feature: #140 - 프로필 편집 이미지뷰 추가
  BestWish/Presentation/Scene/MyPage/MyPageMain/ViewController/Reusable/MyPageCell.swift
  BestWish/Presentation/Scene/MyPage/ProfileUpdate/ViewController/Subview/ProfileUpdateView.swift
  BestWish/Presentation/Scene/Onboarding/ViewController/Subview/OnboardingSecondView.swift
  BestWish/Resource/Assets.xcassets/Profile/profileEdit.imageset/Contents.json
  BestWish/Resource/Assets.xcassets/Profile/profileEdit.imageset/profileEdit.png
  BestWish/Resource/Assets.xcassets/Profile/profileEdit.imageset/profileEdit@2x.png
  BestWish/Resource/Assets.xcassets/Profile/profileEdit.imageset/profileEdit@3x.png
Labels: ✨ Feature, 수현

#142 Refactor/#139 platform enum modify
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/SceneDelegate.swift
  BestWish/Data/Network/Manager/ProductSync/ProductSyncManager.swift
  BestWish/Data/Repository/WishListRepositoryImpl.swift
  BestWish/Data/Util/Platform+Util.swift
  BestWish/Domain/Entity/PlatformEntity.swift
  BestWish/Domain/Entity/ProductMetaData.swift
  BestWish/Domain/Entity/SharePlatform.swift
  BestWish/Presentation/Extension/PlatformEntity+Extension.swift
  BestWish/Presentation/Scene/Anlaysis/ViewModel/AnalysisViewModel.swift
  BestWish/Presentation/Scene/Home/SectionModel/HomeSectionModel.swift
  BestWish/Presentation/Scene/Home/Util/PlatformImage.swift
  BestWish/Presentation/Scene/Home/ViewController/HomeViewController.swift
  BestWish/Presentation/Scene/Home/ViewController/PlatformEditViewController.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/PlatformEditView.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/PlatformEditHeaderView.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListFilterCell.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/WishListEditView.swift
  BestWish/Presentation/Scene/Home/ViewController/WishListEditViewController.swift
  BestWish/Presentation/Scene/Home/ViewModel/HomeViewModel.swift
  BestWish/Presentation/Scene/Home/ViewModel/PlatformEditViewModel.swift
Labels: 🔨 Refactor, 래훈

#147 Hotfix/config error
  BestWish.xcodeproj/project.pbxproj
Labels: 🔥 Hotfix, 🐞 BugFix, 래훈, 영웅, 수현, 세준, 📲 Release

#150 hotfix: 14 -> 15
  BestWish.xcodeproj/project.pbxproj
Labels: 🔥 Hotfix, 세준, 📲 Release

#151 Refactor-Test/#134 AccountRepository 테스트
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/DIContainer.swift
  BestWish/Data/KeyChain/Manager/KeyChainManager.swift
  BestWish/Data/KeyChain/Manager/KeyChainManagerImpl.swift
  BestWish/Data/Network/Manager/OAuth/SupabaseOAuthManager.swift
  BestWish/Data/Network/Manager/OAuth/SupabaseOAuthManagerImpl.swift
  BestWish/Data/Network/Manager/SocialLogin/Apple/AppleLogin.swift
  BestWish/Data/Network/Manager/SocialLogin/Kakao/KakaoLogin.swift
  BestWish/Data/Repository/AccountRepositoryImpl.swift
  BestWishTests/RepositoryTests/AccountRepository/AccountRepositoryTests.swift
  BestWishTests/RepositoryTests/AccountRepository/Mock/MockKeyChainManager.swift
  BestWishTests/RepositoryTests/AccountRepository/Mock/MockSupabaseOAuthManager.swift
  BestWishTests/UseCaseTests/UserInfoUseCase/Mock/MockUserInfoRepository.swift
  BestWishTests/ViewModelTests/MyPageViewModel/Mock/MockAccountUseCase.swift
Labels: 🔨 Refactor, ✅ Test, 수현

#158 Hotfix/#152 platform complete button issue
  .github/workflows/deploy.yml
  BestWish.xcodeproj/project.pbxproj
  BestWish/Presentation/Scene/Home/ViewController/PlatformEditViewController.swift
  BestWish/Presentation/Scene/Home/ViewModel/PlatformEditViewModel.swift
Labels: 🔥 Hotfix, 래훈

#160 Bugfix/#154 UI performance fix
  BestWish/Presentation/Scene/Anlaysis/ViewController/Resuable/AttributeCell.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/Resuable/KeywordCell.swift
  BestWish/Presentation/Scene/Anlaysis/ViewController/SubView/AnalaysisView.swift
  BestWish/Presentation/Scene/Camera/ViewController/CameraViewController.swift
  BestWish/Presentation/Scene/Camera/ViewController/ImageEditViewController.swift
  BestWish/Presentation/Scene/TabBar/View/TabBarView.swift
Labels: 🐞 BugFix, 영웅

#171 Fix/#163 share extension
  BestWish.xcodeproj/project.pbxproj
  BestWish/App/SceneDelegate.swift
  BestWish/Data/Network/Manager/Supabase/SupabaseManager.swift
  BestWish/Presentation/Scene/Home/ViewController/Subview/Reusable/WishListEmptyCell.swift
  BestWish/Resource/Info.plist
  BestWishShareExtension/Resources/Presentation/Share/ShareView.swift
  BestWishShareExtension/Resources/Presentation/Share/ShareViewController.swift
Labels: ✨ Feature, 수현, 🔥 Fix

#173 docs: README.md 초안 작성
  README.md
Labels: 📃 Docs, 수현
